spring:
  application:
    name: notificacao-service

  # RABBITMQ CONFIG
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    # REENVIO DE MENSAGENS
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 5s
          multiplier: 2
    template:
      exchange: pedidos.v1.pedido-criado
      dlx:
        exchange: pedidos.v1.pedido-criado.dlx
    queue:
      name: pedidos.v1.pedido-criado.gerar-notificacao
      dlq:
        name: pedidos.v1.pedido-criado.gerar-notificacao.dlq

  # SPRING MAIL
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false