spring:
  application:
    name: processador

  rabbitmq:
    template:
      exchange: pedidos.v1.pedido-criado
    host: localhost
    username: rabbitmq
    password: rabbitmq
    port: 5672
    queue:
      name: pedidos.v1.pedido-criado.gerar-processamento

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pedidos-api}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update